apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: 510280374120.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2:mysql-v0.1                      # MySQL container image
      ports:
        - containerPort: 3306                # MySQL port
      env:
        - name: MYSQL_ROOT_PASSWORD          # Root password for MySQL
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE               # Initial database to create
          value: webapp_db
