apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: web-app
spec:
  containers:
    - name: web-app-container
      image: <image-name>           # Replace with your web app image URL from Amazon ECR
      ports:
        - containerPort: 80         # Port the web app listens on
      env:
        - name: DATABASE_HOST       # Host for the MySQL database (set in MySQL service)
          value: mysql-service
        - name: DATABASE_USER       # Database username
          value: root
        - name: DATABASE_PASSWORD   # Database password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
